std = "lua51"
max_line_length = false
codes = true
exclude_files = {
	"**/libs",
}
ignore = {
	"11/SLASH_.*", -- slash handlers
	"11/BINDING_.*", -- keybinds
	"1/[A-Z][A-Z][A-Z0-9_]+", -- three letter+ constants
	"211", -- Unused local variable
	"212", -- Unused argument
	"213", -- Unused loop variable
	"432/self", -- Shadowing an upvalue argument
}
globals = {
	-- Addons
	"ElvUI",
	"LibStub",
	"Tukui",

	-- wow std api
	"abs",
	"acos",
	"asin",
	"atan",
	"atan2",
	"bit",
	"ceil",
	"cos",
	"date",
	"debuglocals",
	"debugprofilestart",
	"debugprofilestop",
	"debugstack",
	"deg",
	"difftime",
	"exp",
	"fastrandom",
	"floor",
	"forceinsecure",
	"foreach",
	"foreachi",
	"format",
	"frexp",
	"geterrorhandler",
	"getn",
	"gmatch",
	"gsub",
	"hooksecurefunc",
	"issecretvalue",
	"issecure",
	"issecurevariable",
	"ldexp",
	"log",
	"log10",
	"max",
	"min",
	"mod",
	"rad",
	"random",
	"scrub",
	"securecall",
	"seterrorhandler",
	"sin",
	"sort",
	"sqrt",
	"strbyte",
	"strchar",
	"strcmputf8i",
	"strconcat",
	"strfind",
	"string.join",
	"strjoin",
	"strlen",
	"strlenutf8",
	"strlower",
	"strmatch",
	"strrep",
	"strrev",
	"strsplit",
	"strsub",
	"strtrim",
	"strupper",
	"table.wipe",
	"tan",
	"time",
	"tinsert",
	"tremove",
	"wipe",

	-- FrameXML
	"CanOpenPanels",
	"ChatTypeInfo",
	"CopyTable",
	"FriendsFrame",
	"GameFontNormal",
	"GameTooltip",
	"GameTooltip_Hide",
	"GetUIPanel",
	"GetUIPanelWidth",
	"SecondsToTime",
	"SlashCmdList",
	"UIPanelWindows",
	"UIParent",
	"tContains",

	-- API
	"Ambiguate",
	"BNGetFriendIndex",
	"BNInviteFriend",
	"BNSendWhisper",
	"C_AddOns",
	"C_BattleNet",
	"C_ChatInfo",
	"C_GuildInfo",
	"C_Item",
	"C_Map",
	"C_PaperDollInfo",
	"C_PartyInfo",
	"C_Spell",
	"C_Timer",
	"C_UnitAuras",
	"CombatLogGetCurrentEventInfo",
	"CreateFrame",
	"DemoteAssistant",
	"DoReadyCheck",
	"EJ_GetEncounterInfo",
	"GetAverageItemLevel",
	"GetBattlefieldStatus",
	"GetCVarBool",
	"GetChannelDisplayInfo",
	"GetChannelName",
	"GetGuildInfo",
	"GetGuildRosterInfo",
	"GetInstanceInfo",
	"GetInventoryItemLink",
	"GetLFGMode",
	"GetLocale",
	"GetMaxBattlefieldID",
	"GetMaxLevelForLatestExpansion",
	"GetNumDisplayChannels",
	"GetNumGroupMembers",
	"GetNumGuildMembers",
	"GetNumSubgroupMembers",
	"GetRaidDifficultyID",
	"GetRaidRosterInfo",
	"GetRaidTargetIndex",
	"GetReadyCheckStatus",
	"GetReadyCheckTimeLeft",
	"GetRealZoneText",
	"GetRealmName",
	"GetSpecializationRoleByID",
	"GetTime",
	"GuildControlGetNumRanks",
	"GuildControlGetRankName",
	"InCombatLockdown",
	"IsControlKeyDown",
	"IsEncounterInProgress",
	"IsEveryoneAssistant",
	"IsGuildMember",
	"IsInGroup",
	"IsInGuild",
	"IsInInstance",
	"IsInRaid",
	"IsShiftKeyDown",
	"PlaySound",
	"PromoteToAssistant",
	"SendChatMessage",
	"SetEveryoneIsAssistant",
	"SetPortraitToTexture",
	"SetRaidDifficulties",
	"StopSound",
	"UninviteUnit",
	"UnitAffectingCombat",
	"UnitCastingInfo",
	"UnitChannelInfo",
	"UnitClass",
	"UnitClassBase",
	"UnitExists",
	"UnitFactionGroup",
	"UnitGUID",
	"UnitGroupRolesAssigned",
	"UnitHealth",
	"UnitHealthMax",
	"UnitInBattleground",
	"UnitInParty",
	"UnitInRaid",
	"UnitInRange",
	"UnitIsConnected",
	"UnitIsDead",
	"UnitIsDeadOrGhost",
	"UnitIsFeignDeath",
	"UnitIsGhost",
	"UnitIsGroupAssistant",
	"UnitIsGroupLeader",
	"UnitIsInMyGuild",
	"UnitIsPlayer",
	"UnitIsUnit",
	"UnitIsVisible",
	"UnitLevel",
	"UnitName",
	"UnitRace",
}
